server:
  port: ${PORT:8080}

spring:
  security:
    cors:
      allowed-origins: 
        - https://diplomafinalx.onrender.com
        - http://localhost:3002
        - http://localhost:3004
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: '*'
      allow-credentials: true

# ...existing config...
